/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.19
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#include "Python.h"

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;	
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;	
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;  /**/
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;  /**/
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Flags for pointer conversion */

#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

/* Exception handling in wrappers */
#define SWIG_fail   goto fail

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink(void);
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu = 0;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;
  PyObject  *pyobj = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  }  
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_FromString("this");
    pyobj = obj;
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) { Py_DECREF(obj); }
      return 0;
    } else {
      if (newref) { Py_DECREF(obj); }
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) { Py_DECREF(obj); }
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }

  if ((pyobj) && (flags & SWIG_POINTER_DISOWN)) {
      PyObject *zero = PyInt_FromLong(0);
      PyObject_SetAttrString(pyobj,(char*)"thisown",zero);
      Py_DECREF(zero);
  }
  return 0;

type_error:
  if (flags & SWIG_POINTER_EXCEPTION) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[1024];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (inst) {
      if (own) {
	PyObject *n = PyInt_FromLong(1);
	PyObject_SetAttrString(inst,(char*)"thisown",n);
	Py_DECREF(n);
      }
      robj = inst;
    }
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_idmef_object_value_list_t swig_types[0] 
#define  SWIGTYPE_p_idmef_object_list_t swig_types[1] 
#define  SWIGTYPE_p_prelude_db_message_ident_list_t swig_types[2] 
#define  SWIGTYPE_p_int16_t swig_types[3] 
#define  SWIGTYPE_p_uint16_t swig_types[4] 
#define  SWIGTYPE_p_prelude_sql_field_t swig_types[5] 
#define  SWIGTYPE_p_prelude_db_selected_object_t swig_types[6] 
#define  SWIGTYPE_p_idmef_object_t swig_types[7] 
#define  SWIGTYPE_p_prelude_sql_row_t swig_types[8] 
#define  SWIGTYPE_p_void swig_types[9] 
#define  SWIGTYPE_p_prelude_sql_connection_t swig_types[10] 
#define  SWIGTYPE_p_prelude_db_connection_t swig_types[11] 
#define  SWIGTYPE_p_prelude_db_object_selection_t swig_types[12] 
#define  SWIGTYPE_p_idmef_message_t swig_types[13] 
#define  SWIGTYPE_p_idmef_relation_t swig_types[14] 
#define  SWIGTYPE_p_prelude_db_interface_t swig_types[15] 
#define  SWIGTYPE_p_prelude_db_connection_data_t swig_types[16] 
#define  SWIGTYPE_p_prelude_sql_connection_data_t swig_types[17] 
#define  SWIGTYPE_p_prelude_db_message_ident_t swig_types[18] 
#define  SWIGTYPE_p_idmef_criteria_t swig_types[19] 
#define  SWIGTYPE_p_prelude_sql_table_t swig_types[20] 
#define  SWIGTYPE_p_prelude_strbuf_t swig_types[21] 
#define  SWIGTYPE_p_idmef_string_t swig_types[22] 
#define  SWIGTYPE_p_idmef_criterion_value_t swig_types[23] 
#define  SWIGTYPE_p_idmef_value_t swig_types[24] 
static swig_type_info *swig_types[26];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    init_preludedb

#define SWIG_name    "_preludedb"

#include <pthread.h>
#include <libprelude/list.h>
#include <libprelude/idmef.h>
#include "db-type.h"
#include "db.h"
#include "sql-connection-data.h"
#include "sql.h"
#include "db-message-ident.h"
#include "db-connection.h"
#include "db-connection-data.h"
#include "db-object-selection.h"
#include "db-interface.h"
#include "db-interface-string.h"


#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_prelude_db_init(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int result;
    
    if(!PyArg_ParseTuple(args,(char *)":prelude_db_init")) goto fail;
    result = (int)prelude_db_init();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_shutdown(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    
    if(!PyArg_ParseTuple(args,(char *)":prelude_db_shutdown")) goto fail;
    prelude_db_shutdown();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_selected_object_new(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    idmef_object_t *arg1 = (idmef_object_t *) 0 ;
    int arg2 ;
    prelude_db_selected_object_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:prelude_db_selected_object_new",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_idmef_object_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_selected_object_t *)prelude_db_selected_object_new(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_selected_object_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_selected_object_new_string(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    prelude_db_selected_object_t *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:prelude_db_selected_object_new_string",&arg1)) goto fail;
    result = (prelude_db_selected_object_t *)prelude_db_selected_object_new_string((char const *)arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_selected_object_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_selected_object_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_selected_object_t *arg1 = (prelude_db_selected_object_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_selected_object_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_selected_object_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_selected_object_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_selected_object_get_object(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_selected_object_t *arg1 = (prelude_db_selected_object_t *) 0 ;
    idmef_object_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_selected_object_get_object",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_selected_object_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (idmef_object_t *)prelude_db_selected_object_get_object(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_idmef_object_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_selected_object_get_flags(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_selected_object_t *arg1 = (prelude_db_selected_object_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_selected_object_get_flags",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_selected_object_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_selected_object_get_flags(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_object_selection_new(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_object_selection_t *result;
    
    if(!PyArg_ParseTuple(args,(char *)":prelude_db_object_selection_new")) goto fail;
    result = (prelude_db_object_selection_t *)prelude_db_object_selection_new();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_object_selection_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_object_selection_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_object_selection_t *arg1 = (prelude_db_object_selection_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_object_selection_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_object_selection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_object_selection_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_object_selection_add(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_object_selection_t *arg1 = (prelude_db_object_selection_t *) 0 ;
    prelude_db_selected_object_t *arg2 = (prelude_db_selected_object_t *) 0 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_db_object_selection_add",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_object_selection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_selected_object_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_object_selection_add(arg1,arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_object_selection_get_next(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_object_selection_t *arg1 = (prelude_db_object_selection_t *) 0 ;
    prelude_db_selected_object_t *arg2 = (prelude_db_selected_object_t *) 0 ;
    prelude_db_selected_object_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_db_object_selection_get_next",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_object_selection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_selected_object_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_selected_object_t *)prelude_db_object_selection_get_next(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_selected_object_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_message_ident_new(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    uint64_t arg1 ;
    uint64_t arg2 ;
    prelude_db_message_ident_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_db_message_ident_new",&obj0,&obj1)) goto fail;
    arg1 = (uint64_t) PyLong_AsUnsignedLongLong(obj0);
    if (PyErr_Occurred()) SWIG_fail;
    arg2 = (uint64_t) PyLong_AsUnsignedLongLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    result = (prelude_db_message_ident_t *)prelude_db_message_ident_new(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_message_ident_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_message_ident_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_t *arg1 = (prelude_db_message_ident_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_message_ident_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_message_ident_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_message_ident_get_analyzerid(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_t *arg1 = (prelude_db_message_ident_t *) 0 ;
    uint64_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_message_ident_get_analyzerid",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (uint64_t)prelude_db_message_ident_get_analyzerid(arg1);
    
    resultobj = PyLong_FromUnsignedLongLong(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_message_ident_get_ident(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_t *arg1 = (prelude_db_message_ident_t *) 0 ;
    uint64_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_message_ident_get_ident",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (uint64_t)prelude_db_message_ident_get_ident(arg1);
    
    resultobj = PyLong_FromUnsignedLongLong(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_new(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    char *arg2 ;
    prelude_db_connection_data_t *arg3 = (prelude_db_connection_data_t *) 0 ;
    prelude_db_interface_t *result;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"ssO:prelude_db_interface_new",&arg1,&arg2,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_prelude_db_connection_data_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_interface_t *)prelude_db_interface_new((char const *)arg1,(char const *)arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_interface_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_interface_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_enable_message_cache(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    char *arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:prelude_db_interface_enable_message_cache",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_enable_message_cache(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_disable_message_cache(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_disable_message_cache",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_interface_disable_message_cache(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_name",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_db_interface_get_name(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_format(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_format",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_db_interface_get_format(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_connect(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_connect",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_connect(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_alert_ident_list(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    idmef_criteria_t *arg2 = (idmef_criteria_t *) 0 ;
    int arg3 ;
    int arg4 ;
    prelude_db_message_ident_list_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOii:prelude_db_interface_get_alert_ident_list",&obj0,&obj1,&arg3,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_idmef_criteria_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_message_ident_list_t *)prelude_db_interface_get_alert_ident_list(arg1,arg2,arg3,arg4);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_message_ident_list_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_heartbeat_ident_list(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    idmef_criteria_t *arg2 = (idmef_criteria_t *) 0 ;
    int arg3 ;
    int arg4 ;
    prelude_db_message_ident_list_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOii:prelude_db_interface_get_heartbeat_ident_list",&obj0,&obj1,&arg3,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_idmef_criteria_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_message_ident_list_t *)prelude_db_interface_get_heartbeat_ident_list(arg1,arg2,arg3,arg4);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_message_ident_list_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_alert_ident_list_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_list_t *arg1 = (prelude_db_message_ident_list_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_alert_ident_list_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_interface_alert_ident_list_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_heartbeat_ident_list_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_list_t *arg1 = (prelude_db_message_ident_list_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_heartbeat_ident_list_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_interface_heartbeat_ident_list_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_alert_ident_list_len(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_list_t *arg1 = (prelude_db_message_ident_list_t *) 0 ;
    unsigned int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_alert_ident_list_len",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (unsigned int)prelude_db_interface_get_alert_ident_list_len(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_heartbeat_ident_list_len(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_list_t *arg1 = (prelude_db_message_ident_list_t *) 0 ;
    unsigned int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_heartbeat_ident_list_len",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (unsigned int)prelude_db_interface_get_heartbeat_ident_list_len(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_next_alert_ident(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_list_t *arg1 = (prelude_db_message_ident_list_t *) 0 ;
    prelude_db_message_ident_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_next_alert_ident",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_message_ident_t *)prelude_db_interface_get_next_alert_ident(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_message_ident_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_next_heartbeat_ident(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_message_ident_list_t *arg1 = (prelude_db_message_ident_list_t *) 0 ;
    prelude_db_message_ident_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_next_heartbeat_ident",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_message_ident_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_message_ident_t *)prelude_db_interface_get_next_heartbeat_ident(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_message_ident_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_alert(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_message_ident_t *arg2 = (prelude_db_message_ident_t *) 0 ;
    idmef_object_list_t *arg3 = (idmef_object_list_t *) 0 ;
    idmef_message_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:prelude_db_interface_get_alert",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_idmef_object_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (idmef_message_t *)prelude_db_interface_get_alert(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_idmef_message_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_heartbeat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_message_ident_t *arg2 = (prelude_db_message_ident_t *) 0 ;
    idmef_object_list_t *arg3 = (idmef_object_list_t *) 0 ;
    idmef_message_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:prelude_db_interface_get_heartbeat",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_idmef_object_list_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (idmef_message_t *)prelude_db_interface_get_heartbeat(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_idmef_message_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_delete_alert(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_message_ident_t *arg2 = (prelude_db_message_ident_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_db_interface_delete_alert",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_delete_alert(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_delete_heartbeat(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_message_ident_t *arg2 = (prelude_db_message_ident_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_db_interface_delete_heartbeat",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_message_ident_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_delete_heartbeat(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_insert_idmef_message(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    idmef_message_t *arg2 = (idmef_message_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_db_interface_insert_idmef_message",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_idmef_message_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_insert_idmef_message(arg1,(idmef_message_t const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_select_values(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_object_selection_t *arg2 = (prelude_db_object_selection_t *) 0 ;
    idmef_criteria_t *arg3 = (idmef_criteria_t *) 0 ;
    int arg4 ;
    int arg5 ;
    int arg6 ;
    void *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOiii:prelude_db_interface_select_values",&obj0,&obj1,&obj2,&arg4,&arg5,&arg6)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_db_object_selection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_idmef_criteria_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (void *)prelude_db_interface_select_values(arg1,arg2,arg3,arg4,arg5,arg6);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_values(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    void *arg2 = (void *) 0 ;
    prelude_db_object_selection_t *arg3 = (prelude_db_object_selection_t *) 0 ;
    idmef_object_value_list_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj2 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:prelude_db_interface_get_values",&obj0,&obj1,&obj2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_prelude_db_object_selection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (idmef_object_value_list_t *)prelude_db_interface_get_values(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_idmef_object_value_list_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_connection(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_connection_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_connection",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_connection_t *)prelude_db_interface_get_connection(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_connection_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_get_connection_data(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    prelude_db_connection_data_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_get_connection_data",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_connection_data_t *)prelude_db_interface_get_connection_data(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_connection_data_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_errno(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_errno",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_errno(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_error(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_error",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_db_interface_error(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_disconnect(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_interface_disconnect",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_interface_disconnect(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_interface_new_string(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg1 ;
    prelude_db_interface_t *result;
    
    if(!PyArg_ParseTuple(args,(char *)"s:prelude_db_interface_new_string",&arg1)) goto fail;
    result = (prelude_db_interface_t *)prelude_db_interface_new_string((char const *)arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_interface_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_connection_new(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    int arg1 ;
    void *arg2 = (void *) 0 ;
    prelude_db_connection_t *result;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"iO:prelude_db_connection_new",&arg1,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, 0, SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_db_connection_t *)prelude_db_connection_new((prelude_db_type_t )arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_db_connection_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_connection_get_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_connection_t *arg1 = (prelude_db_connection_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_connection_get_type",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_db_connection_get_type(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_connection_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_connection_t *arg1 = (prelude_db_connection_t *) 0 ;
    void *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_connection_get",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (void *)prelude_db_connection_get(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_void, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_connection_get_sql(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_connection_t *arg1 = (prelude_db_connection_t *) 0 ;
    prelude_sql_connection_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_connection_get_sql",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_sql_connection_t *)prelude_db_connection_get_sql(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_sql_connection_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_db_connection_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_db_connection_t *arg1 = (prelude_db_connection_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_db_connection_destroy",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_db_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_db_connection_destroy(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_query__varargs__(PyObject *self, PyObject *args, PyObject *varargs) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    char *arg2 ;
    void *arg3 = 0 ;
    prelude_sql_table_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:prelude_sql_query",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_sql_table_t *)prelude_sql_query(arg1,(char const *)arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_sql_table_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_query(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *varargs;
    PyObject *newargs;
    
    newargs = PyTuple_GetSlice(args,0,2);
    varargs = PyTuple_GetSlice(args,2,PyTuple_Size(args)+1);
    resultobj = _wrap_prelude_sql_query__varargs__(self,newargs,varargs);
    Py_XDECREF(newargs);
    Py_XDECREF(varargs);
    return resultobj;
}


static PyObject *_wrap_prelude_sql_errno(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_errno",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_errno(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_error(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_error",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_sql_error(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_escape(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    char *arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:prelude_sql_escape",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_sql_escape(arg1,(char const *)arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_limit_offset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    int arg2 ;
    int arg3 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oii:prelude_sql_limit_offset",&obj0,&arg2,&arg3)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_sql_limit_offset(arg1,arg2,arg3);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_build_criterion(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    prelude_strbuf_t *arg2 = (prelude_strbuf_t *) 0 ;
    char *arg3 ;
    idmef_relation_t arg4 ;
    idmef_criterion_value_t *arg5 = (idmef_criterion_value_t *) 0 ;
    int result;
    idmef_relation_t *argp4 ;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    PyObject * obj3 = 0 ;
    PyObject * obj4 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOsOO:prelude_sql_build_criterion",&obj0,&obj1,&arg3,&obj3,&obj4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_prelude_strbuf_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    if ((SWIG_ConvertPtr(obj3,(void **) &argp4, SWIGTYPE_p_idmef_relation_t,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg4 = *argp4; 
    if ((SWIG_ConvertPtr(obj4,(void **) &arg5, SWIGTYPE_p_idmef_criterion_value_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_build_criterion(arg1,arg2,(char const *)arg3,arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_begin(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_begin",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_begin(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_commit(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_commit",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_commit(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_rollback(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_rollback",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_rollback(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_close(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_close",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_sql_close(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_connect(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_connection_data_t *arg1 = (prelude_sql_connection_data_t *) 0 ;
    prelude_sql_connection_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_connect",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_data_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_sql_connection_t *)prelude_sql_connect(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_sql_connection_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_insert__varargs__(PyObject *self, PyObject *args, PyObject *varargs) {
    PyObject *resultobj;
    prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
    char *arg2 ;
    char *arg3 ;
    char *arg4 ;
    void *arg5 = 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Osss:prelude_sql_insert",&obj0,&arg2,&arg3,&arg4)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_insert(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_insert(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    PyObject *varargs;
    PyObject *newargs;
    
    newargs = PyTuple_GetSlice(args,0,4);
    varargs = PyTuple_GetSlice(args,4,PyTuple_Size(args)+1);
    resultobj = _wrap_prelude_sql_insert__varargs__(self,newargs,varargs);
    Py_XDECREF(newargs);
    Py_XDECREF(varargs);
    return resultobj;
}


static PyObject *_wrap_prelude_sql_idmef_relation_to_string(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    idmef_relation_t arg1 ;
    char *result;
    idmef_relation_t *argp1 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_idmef_relation_to_string",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &argp1, SWIGTYPE_p_idmef_relation_t,SWIG_POINTER_EXCEPTION) == -1)) SWIG_fail;
    arg1 = *argp1; 
    result = (char *)prelude_sql_idmef_relation_to_string(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_table_free(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_table_free",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_sql_table_free(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    unsigned int arg2 ;
    char *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_sql_field_name",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (unsigned int) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    result = (char *)prelude_sql_field_name(arg1,arg2);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_num(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    char *arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:prelude_sql_field_num",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_field_num(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    unsigned int arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_sql_field_type",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (unsigned int) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    result = (int)prelude_sql_field_type(arg1,arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_type_by_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    char *arg2 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:prelude_sql_field_type_by_name",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_field_type_by_name(arg1,(char const *)arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_fields_num(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    unsigned int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_fields_num",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (unsigned int)prelude_sql_fields_num(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_rows_num(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    unsigned int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_rows_num",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (unsigned int)prelude_sql_rows_num(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_row_fetch(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
    prelude_sql_row_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_row_fetch",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_sql_row_t *)prelude_sql_row_fetch(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_sql_row_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_row_free(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_row_t *arg1 = (prelude_sql_row_t *) 0 ;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_row_free",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_row_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    prelude_sql_row_free(arg1);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_fetch(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_row_t *arg1 = (prelude_sql_row_t *) 0 ;
    unsigned int arg2 ;
    prelude_sql_field_t *result;
    PyObject * obj0 = 0 ;
    PyObject * obj1 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:prelude_sql_field_fetch",&obj0,&obj1)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_row_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    arg2 = (unsigned int) PyInt_AsLong(obj1);
    if (PyErr_Occurred()) SWIG_fail;
    result = (prelude_sql_field_t *)prelude_sql_field_fetch(arg1,arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_sql_field_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_fetch_by_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_row_t *arg1 = (prelude_sql_row_t *) 0 ;
    char *arg2 ;
    prelude_sql_field_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:prelude_sql_field_fetch_by_name",&obj0,&arg2)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_row_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (prelude_sql_field_t *)prelude_sql_field_fetch_by_name(arg1,(char const *)arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_prelude_sql_field_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_info_type(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    int result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_info_type",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int)prelude_sql_field_info_type(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    char *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (char *)prelude_sql_field_value(arg1);
    
    resultobj = result ? PyString_FromString(result) : Py_BuildValue((char*)"");
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_int16(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    int16_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_int16",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = prelude_sql_field_value_int16(arg1);
    
    {
        int16_t * resultptr;
        resultptr = (int16_t *) malloc(sizeof(int16_t));
        memmove(resultptr, &result, sizeof(int16_t));
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_int16_t, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_uint16(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    uint16_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_uint16",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = prelude_sql_field_value_uint16(arg1);
    
    {
        uint16_t * resultptr;
        resultptr = (uint16_t *) malloc(sizeof(uint16_t));
        memmove(resultptr, &result, sizeof(uint16_t));
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_uint16_t, 1);
    }
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_int32(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    int32_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_int32",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int32_t)prelude_sql_field_value_int32(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_uint32(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    uint32_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_uint32",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (uint32_t)prelude_sql_field_value_uint32(arg1);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_int64(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    int64_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_int64",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (int64_t)prelude_sql_field_value_int64(arg1);
    
    resultobj = PyLong_FromLongLong(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_uint64(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    uint64_t result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_uint64",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (uint64_t)prelude_sql_field_value_uint64(arg1);
    
    resultobj = PyLong_FromUnsignedLongLong(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_float(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    float result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_float",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (float)prelude_sql_field_value_float(arg1);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_double(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    double result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_double",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (double)prelude_sql_field_value_double(arg1);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_string(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    idmef_string_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_string",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (idmef_string_t *)prelude_sql_field_value_string(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_idmef_string_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyObject *_wrap_prelude_sql_field_value_idmef(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    prelude_sql_field_t *arg1 = (prelude_sql_field_t *) 0 ;
    idmef_value_t *result;
    PyObject * obj0 = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:prelude_sql_field_value_idmef",&obj0)) goto fail;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_prelude_sql_field_t,SWIG_POINTER_EXCEPTION | 0 )) == -1) SWIG_fail;
    result = (idmef_value_t *)prelude_sql_field_value_idmef(arg1);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_idmef_value_t, 0);
    return resultobj;
    fail:
    return NULL;
}


static PyMethodDef SwigMethods[] = {
	 { (char *)"prelude_db_init", _wrap_prelude_db_init, METH_VARARGS },
	 { (char *)"prelude_db_shutdown", _wrap_prelude_db_shutdown, METH_VARARGS },
	 { (char *)"prelude_db_selected_object_new", _wrap_prelude_db_selected_object_new, METH_VARARGS },
	 { (char *)"prelude_db_selected_object_new_string", _wrap_prelude_db_selected_object_new_string, METH_VARARGS },
	 { (char *)"prelude_db_selected_object_destroy", _wrap_prelude_db_selected_object_destroy, METH_VARARGS },
	 { (char *)"prelude_db_selected_object_get_object", _wrap_prelude_db_selected_object_get_object, METH_VARARGS },
	 { (char *)"prelude_db_selected_object_get_flags", _wrap_prelude_db_selected_object_get_flags, METH_VARARGS },
	 { (char *)"prelude_db_object_selection_new", _wrap_prelude_db_object_selection_new, METH_VARARGS },
	 { (char *)"prelude_db_object_selection_destroy", _wrap_prelude_db_object_selection_destroy, METH_VARARGS },
	 { (char *)"prelude_db_object_selection_add", _wrap_prelude_db_object_selection_add, METH_VARARGS },
	 { (char *)"prelude_db_object_selection_get_next", _wrap_prelude_db_object_selection_get_next, METH_VARARGS },
	 { (char *)"prelude_db_message_ident_new", _wrap_prelude_db_message_ident_new, METH_VARARGS },
	 { (char *)"prelude_db_message_ident_destroy", _wrap_prelude_db_message_ident_destroy, METH_VARARGS },
	 { (char *)"prelude_db_message_ident_get_analyzerid", _wrap_prelude_db_message_ident_get_analyzerid, METH_VARARGS },
	 { (char *)"prelude_db_message_ident_get_ident", _wrap_prelude_db_message_ident_get_ident, METH_VARARGS },
	 { (char *)"prelude_db_interface_new", _wrap_prelude_db_interface_new, METH_VARARGS },
	 { (char *)"prelude_db_interface_destroy", _wrap_prelude_db_interface_destroy, METH_VARARGS },
	 { (char *)"prelude_db_interface_enable_message_cache", _wrap_prelude_db_interface_enable_message_cache, METH_VARARGS },
	 { (char *)"prelude_db_interface_disable_message_cache", _wrap_prelude_db_interface_disable_message_cache, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_name", _wrap_prelude_db_interface_get_name, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_format", _wrap_prelude_db_interface_get_format, METH_VARARGS },
	 { (char *)"prelude_db_interface_connect", _wrap_prelude_db_interface_connect, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_alert_ident_list", _wrap_prelude_db_interface_get_alert_ident_list, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_heartbeat_ident_list", _wrap_prelude_db_interface_get_heartbeat_ident_list, METH_VARARGS },
	 { (char *)"prelude_db_interface_alert_ident_list_destroy", _wrap_prelude_db_interface_alert_ident_list_destroy, METH_VARARGS },
	 { (char *)"prelude_db_interface_heartbeat_ident_list_destroy", _wrap_prelude_db_interface_heartbeat_ident_list_destroy, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_alert_ident_list_len", _wrap_prelude_db_interface_get_alert_ident_list_len, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_heartbeat_ident_list_len", _wrap_prelude_db_interface_get_heartbeat_ident_list_len, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_next_alert_ident", _wrap_prelude_db_interface_get_next_alert_ident, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_next_heartbeat_ident", _wrap_prelude_db_interface_get_next_heartbeat_ident, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_alert", _wrap_prelude_db_interface_get_alert, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_heartbeat", _wrap_prelude_db_interface_get_heartbeat, METH_VARARGS },
	 { (char *)"prelude_db_interface_delete_alert", _wrap_prelude_db_interface_delete_alert, METH_VARARGS },
	 { (char *)"prelude_db_interface_delete_heartbeat", _wrap_prelude_db_interface_delete_heartbeat, METH_VARARGS },
	 { (char *)"prelude_db_interface_insert_idmef_message", _wrap_prelude_db_interface_insert_idmef_message, METH_VARARGS },
	 { (char *)"prelude_db_interface_select_values", _wrap_prelude_db_interface_select_values, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_values", _wrap_prelude_db_interface_get_values, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_connection", _wrap_prelude_db_interface_get_connection, METH_VARARGS },
	 { (char *)"prelude_db_interface_get_connection_data", _wrap_prelude_db_interface_get_connection_data, METH_VARARGS },
	 { (char *)"prelude_db_interface_errno", _wrap_prelude_db_interface_errno, METH_VARARGS },
	 { (char *)"prelude_db_interface_error", _wrap_prelude_db_interface_error, METH_VARARGS },
	 { (char *)"prelude_db_interface_disconnect", _wrap_prelude_db_interface_disconnect, METH_VARARGS },
	 { (char *)"prelude_db_interface_new_string", _wrap_prelude_db_interface_new_string, METH_VARARGS },
	 { (char *)"prelude_db_connection_new", _wrap_prelude_db_connection_new, METH_VARARGS },
	 { (char *)"prelude_db_connection_get_type", _wrap_prelude_db_connection_get_type, METH_VARARGS },
	 { (char *)"prelude_db_connection_get", _wrap_prelude_db_connection_get, METH_VARARGS },
	 { (char *)"prelude_db_connection_get_sql", _wrap_prelude_db_connection_get_sql, METH_VARARGS },
	 { (char *)"prelude_db_connection_destroy", _wrap_prelude_db_connection_destroy, METH_VARARGS },
	 { (char *)"prelude_sql_query", _wrap_prelude_sql_query, METH_VARARGS },
	 { (char *)"prelude_sql_errno", _wrap_prelude_sql_errno, METH_VARARGS },
	 { (char *)"prelude_sql_error", _wrap_prelude_sql_error, METH_VARARGS },
	 { (char *)"prelude_sql_escape", _wrap_prelude_sql_escape, METH_VARARGS },
	 { (char *)"prelude_sql_limit_offset", _wrap_prelude_sql_limit_offset, METH_VARARGS },
	 { (char *)"prelude_sql_build_criterion", _wrap_prelude_sql_build_criterion, METH_VARARGS },
	 { (char *)"prelude_sql_begin", _wrap_prelude_sql_begin, METH_VARARGS },
	 { (char *)"prelude_sql_commit", _wrap_prelude_sql_commit, METH_VARARGS },
	 { (char *)"prelude_sql_rollback", _wrap_prelude_sql_rollback, METH_VARARGS },
	 { (char *)"prelude_sql_close", _wrap_prelude_sql_close, METH_VARARGS },
	 { (char *)"prelude_sql_connect", _wrap_prelude_sql_connect, METH_VARARGS },
	 { (char *)"prelude_sql_insert", _wrap_prelude_sql_insert, METH_VARARGS },
	 { (char *)"prelude_sql_idmef_relation_to_string", _wrap_prelude_sql_idmef_relation_to_string, METH_VARARGS },
	 { (char *)"prelude_sql_table_free", _wrap_prelude_sql_table_free, METH_VARARGS },
	 { (char *)"prelude_sql_field_name", _wrap_prelude_sql_field_name, METH_VARARGS },
	 { (char *)"prelude_sql_field_num", _wrap_prelude_sql_field_num, METH_VARARGS },
	 { (char *)"prelude_sql_field_type", _wrap_prelude_sql_field_type, METH_VARARGS },
	 { (char *)"prelude_sql_field_type_by_name", _wrap_prelude_sql_field_type_by_name, METH_VARARGS },
	 { (char *)"prelude_sql_fields_num", _wrap_prelude_sql_fields_num, METH_VARARGS },
	 { (char *)"prelude_sql_rows_num", _wrap_prelude_sql_rows_num, METH_VARARGS },
	 { (char *)"prelude_sql_row_fetch", _wrap_prelude_sql_row_fetch, METH_VARARGS },
	 { (char *)"prelude_sql_row_free", _wrap_prelude_sql_row_free, METH_VARARGS },
	 { (char *)"prelude_sql_field_fetch", _wrap_prelude_sql_field_fetch, METH_VARARGS },
	 { (char *)"prelude_sql_field_fetch_by_name", _wrap_prelude_sql_field_fetch_by_name, METH_VARARGS },
	 { (char *)"prelude_sql_field_info_type", _wrap_prelude_sql_field_info_type, METH_VARARGS },
	 { (char *)"prelude_sql_field_value", _wrap_prelude_sql_field_value, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_int16", _wrap_prelude_sql_field_value_int16, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_uint16", _wrap_prelude_sql_field_value_uint16, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_int32", _wrap_prelude_sql_field_value_int32, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_uint32", _wrap_prelude_sql_field_value_uint32, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_int64", _wrap_prelude_sql_field_value_int64, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_uint64", _wrap_prelude_sql_field_value_uint64, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_float", _wrap_prelude_sql_field_value_float, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_double", _wrap_prelude_sql_field_value_double, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_string", _wrap_prelude_sql_field_value_string, METH_VARARGS },
	 { (char *)"prelude_sql_field_value_idmef", _wrap_prelude_sql_field_value_idmef, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_idmef_object_value_list_t[] = {{"_p_idmef_object_value_list_t", 0, "idmef_object_value_list_t *", 0},{"_p_idmef_object_value_list_t"},{0}};
static swig_type_info _swigt__p_idmef_object_list_t[] = {{"_p_idmef_object_list_t", 0, "idmef_object_list_t *", 0},{"_p_idmef_object_list_t"},{0}};
static swig_type_info _swigt__p_prelude_db_message_ident_list_t[] = {{"_p_prelude_db_message_ident_list_t", 0, "prelude_db_message_ident_list_t *", 0},{"_p_prelude_db_message_ident_list_t"},{0}};
static swig_type_info _swigt__p_int16_t[] = {{"_p_int16_t", 0, "int16_t *", 0},{"_p_int16_t"},{0}};
static swig_type_info _swigt__p_uint16_t[] = {{"_p_uint16_t", 0, "uint16_t *", 0},{"_p_uint16_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_field_t[] = {{"_p_prelude_sql_field_t", 0, "prelude_sql_field_t *", 0},{"_p_prelude_sql_field_t"},{0}};
static swig_type_info _swigt__p_prelude_db_selected_object_t[] = {{"_p_prelude_db_selected_object_t", 0, "prelude_db_selected_object_t *", 0},{"_p_prelude_db_selected_object_t"},{0}};
static swig_type_info _swigt__p_idmef_object_t[] = {{"_p_idmef_object_t", 0, "idmef_object_t *", 0},{"_p_idmef_object_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_row_t[] = {{"_p_prelude_sql_row_t", 0, "prelude_sql_row_t *", 0},{"_p_prelude_sql_row_t"},{0}};
static swig_type_info _swigt__p_void[] = {{"_p_void", 0, "void *", 0},{"_p_void"},{0}};
static swig_type_info _swigt__p_prelude_sql_connection_t[] = {{"_p_prelude_sql_connection_t", 0, "prelude_sql_connection_t *", 0},{"_p_prelude_sql_connection_t"},{0}};
static swig_type_info _swigt__p_prelude_db_connection_t[] = {{"_p_prelude_db_connection_t", 0, "prelude_db_connection_t *", 0},{"_p_prelude_db_connection_t"},{0}};
static swig_type_info _swigt__p_prelude_db_object_selection_t[] = {{"_p_prelude_db_object_selection_t", 0, "prelude_db_object_selection_t *", 0},{"_p_prelude_db_object_selection_t"},{0}};
static swig_type_info _swigt__p_idmef_message_t[] = {{"_p_idmef_message_t", 0, "idmef_message_t *", 0},{"_p_idmef_message_t"},{0}};
static swig_type_info _swigt__p_idmef_relation_t[] = {{"_p_idmef_relation_t", 0, "idmef_relation_t *", 0},{"_p_idmef_relation_t"},{0}};
static swig_type_info _swigt__p_prelude_db_interface_t[] = {{"_p_prelude_db_interface_t", 0, "prelude_db_interface_t *", 0},{"_p_prelude_db_interface_t"},{0}};
static swig_type_info _swigt__p_prelude_db_connection_data_t[] = {{"_p_prelude_db_connection_data_t", 0, "prelude_db_connection_data_t *", 0},{"_p_prelude_db_connection_data_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_connection_data_t[] = {{"_p_prelude_sql_connection_data_t", 0, "prelude_sql_connection_data_t *", 0},{"_p_prelude_sql_connection_data_t"},{0}};
static swig_type_info _swigt__p_prelude_db_message_ident_t[] = {{"_p_prelude_db_message_ident_t", 0, "prelude_db_message_ident_t *", 0},{"_p_prelude_db_message_ident_t"},{0}};
static swig_type_info _swigt__p_idmef_criteria_t[] = {{"_p_idmef_criteria_t", 0, "idmef_criteria_t *", 0},{"_p_idmef_criteria_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_table_t[] = {{"_p_prelude_sql_table_t", 0, "prelude_sql_table_t *", 0},{"_p_prelude_sql_table_t"},{0}};
static swig_type_info _swigt__p_prelude_strbuf_t[] = {{"_p_prelude_strbuf_t", 0, "prelude_strbuf_t *", 0},{"_p_prelude_strbuf_t"},{0}};
static swig_type_info _swigt__p_idmef_string_t[] = {{"_p_idmef_string_t", 0, "idmef_string_t *", 0},{"_p_idmef_string_t"},{0}};
static swig_type_info _swigt__p_idmef_criterion_value_t[] = {{"_p_idmef_criterion_value_t", 0, "idmef_criterion_value_t *", 0},{"_p_idmef_criterion_value_t"},{0}};
static swig_type_info _swigt__p_idmef_value_t[] = {{"_p_idmef_value_t", 0, "idmef_value_t *", 0},{"_p_idmef_value_t"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_idmef_object_value_list_t, 
_swigt__p_idmef_object_list_t, 
_swigt__p_prelude_db_message_ident_list_t, 
_swigt__p_int16_t, 
_swigt__p_uint16_t, 
_swigt__p_prelude_sql_field_t, 
_swigt__p_prelude_db_selected_object_t, 
_swigt__p_idmef_object_t, 
_swigt__p_prelude_sql_row_t, 
_swigt__p_void, 
_swigt__p_prelude_sql_connection_t, 
_swigt__p_prelude_db_connection_t, 
_swigt__p_prelude_db_object_selection_t, 
_swigt__p_idmef_message_t, 
_swigt__p_idmef_relation_t, 
_swigt__p_prelude_db_interface_t, 
_swigt__p_prelude_db_connection_data_t, 
_swigt__p_prelude_sql_connection_data_t, 
_swigt__p_prelude_db_message_ident_t, 
_swigt__p_idmef_criteria_t, 
_swigt__p_prelude_sql_table_t, 
_swigt__p_prelude_strbuf_t, 
_swigt__p_idmef_string_t, 
_swigt__p_idmef_criterion_value_t, 
_swigt__p_idmef_value_t, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_INT,     (char *)"prelude_db_type_invalid", (long) prelude_db_type_invalid, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"prelude_db_type_sql", (long) prelude_db_type_sql, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_FUNCTION_MIN", (long) 0x01, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_FUNCTION_MAX", (long) 0x02, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_FUNCTION_AVG", (long) 0x04, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_FUNCTION_STD", (long) 0x08, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_FUNCTION_COUNT", (long) 0x10, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_GROUP_BY", (long) 0x20, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_ORDER_ASC", (long) 0x40, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PRELUDEDB_SELECTED_OBJECT_ORDER_DESC", (long) 0x80, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_unknown", (long) dbtype_unknown, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_int32", (long) dbtype_int32, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_uint32", (long) dbtype_uint32, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_int64", (long) dbtype_int64, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_uint64", (long) dbtype_uint64, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_float", (long) dbtype_float, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_double", (long) dbtype_double, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_string", (long) dbtype_string, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_void", (long) dbtype_void, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"dbtype_end", (long) dbtype_end, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

