/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.19
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) extern a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#                       define SWIGIMPORT(a) extern a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#                       define SWIGIMPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#                       define SWIGIMPORT(a) a
#               endif
#       endif
#else
#       define SWIGEXPORT(a) a
#       define SWIGIMPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;	
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE

SWIGIMPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGIMPORT(void *)           SWIG_TypeCast(swig_type_info *, void *);
SWIGIMPORT(swig_type_info *) SWIG_TypeDynamicCast(swig_type_info *, void **);
SWIGIMPORT(const char *)     SWIG_TypeName(const swig_type_info *);
SWIGIMPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGIMPORT(void)             SWIG_TypeClientData(swig_type_info *, void *);

#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      if (tc->clientdata) ti->clientdata = tc->clientdata;	
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;  /**/
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;  /**/
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/* Cast a pointer up an inheritance hierarchy */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Dynamic pointer casting. Down an inheritance hierarchy */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) 
{
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
     ty = (*ty->dcast)(ptr);
     if (ty) lastty = ty;
  }
  return lastty;
}

/* Return the name associated with this type */
SWIGRUNTIME(const char *)
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata == clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif

/* -----------------------------------------------------------------------------
 * perl5.swg
 *
 * Perl5 runtime library
 * $Header: /var/lib/cvsd/cvsroot/prelude/libpreludedb/bindings/perl/PreludeDB.c,v 1.6 2003/08/02 21:54:32 nicolasd Exp $
 * ----------------------------------------------------------------------------- */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
/* Needed on some windows machines---since MS plays funny
   games with the header files under C++ */
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* Get rid of free and malloc defined by perl */
#undef free
#undef malloc

#ifndef pTHX_
#define pTHX_
#endif

#include <string.h>
#ifdef __cplusplus
}
#endif

/* Macro to call an XS function */

#ifdef PERL_OBJECT 
#define SWIG_CALLXS(_name) _name(cv,pPerl) 
#else 
#ifndef MULTIPLICITY 
#define SWIG_CALLXS(_name) _name(cv) 
#else 
#define SWIG_CALLXS(_name) _name(PERL_GET_THX, cv) 
#endif 
#endif 

/* Macros for low-level exception handling */
#define SWIG_fail      goto fail
#define SWIG_croak(x)  { if ((_swigerr = (const char *) x)) goto fail; }
#define SWIG_MAX_ERRMSG 256

/* Note: SwigMagicFuncHack is a typedef used to get the C++
   compiler to just shut up already */

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerlObj *pPerl = (CPerlObj *) this;
typedef int (CPerlObj::*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (CPerlObj::*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
#define SWIGCLASS_STATIC
#else
#define MAGIC_PPERL
#define SWIGCLASS_STATIC static
#ifndef MULTIPLICITY
#define SWIG_MAGIC(a,b) (SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(SV *, MAGIC *);

#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(SV *, MAGIC *);
#ifdef __cplusplus
}
#endif


#else
#define SWIG_MAGIC(a,b) (struct interpreter *interp, SV *a, MAGIC *b)
typedef int (*SwigMagicFunc)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
extern "C" {
#endif
typedef int (*SwigMagicFuncHack)(struct interpreter *, SV *, MAGIC *);
#ifdef __cplusplus
}
#endif

#endif
#endif

#if defined(WIN32) && defined(PERL_OBJECT) && !defined(PerlIO_exportFILE)
#define PerlIO_exportFILE(fh,fl) (FILE*)(fh)
#endif

/* Modifications for newer Perl 5.005 releases */

#if !defined(PERL_REVISION) || ((PERL_REVISION >= 5) && ((PERL_VERSION < 5) || ((PERL_VERSION == 5) && (PERL_SUBVERSION < 50))))
#ifndef PL_sv_yes
#define PL_sv_yes sv_yes
#endif
#ifndef PL_sv_undef
#define PL_sv_undef sv_undef
#endif
#ifndef PL_na
#define PL_na na
#endif
#endif

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SWIG_NOINCLUDE

#ifndef PERL_OBJECT
extern int SWIG_ConvertPtr(SV *, void **, swig_type_info *, int flags);
extern void SWIG_MakePtr(SV *, void *, swig_type_info *, int flags);
#else
extern int _SWIG_ConvertPtr(CPerlObj *, SV *, void **, swig_type_info *,int flags);
extern void _SWIG_MakePtr(CPerlObj *, SV *, void *, swig_type_info *, int flags);
#define SWIG_ConvertPtr(a,b,c,d) _SWIG_ConvertPtr(pPerl,a,b,c,d)
#define SWIG_MakePtr(a,b,c,d) _SWIG_MakePtr(pPerl,a,b,c,d)
#endif

#else

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGRUNTIME(int) 
SWIG_ConvertPtr(SV *sv, void **ptr, swig_type_info *_t, int flags)
#else
#define SWIG_ConvertPtr(a,b,c,d) _SWIG_ConvertPtr(pPerl,a,b,c,d)
SWIGRUNTIME(int)
_SWIG_ConvertPtr(CPerlObj *pPerl, SV *sv, void **ptr, swig_type_info *_t, int flags)
#endif
{
  char *_c;
  swig_type_info *tc;
  IV   tmp;

  /* If magical, apply more magic */
  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
	mg = mg_find(tsv,'P');
	if (mg) {
	  SV *rsv = mg->mg_obj;
	  if (sv_isobject(rsv)) {
	    tmp = SvIV((SV*)SvRV(rsv));
	  }
	}
      } else {
	return -1;
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    if (!_t) {
      *(ptr) = (void *) tmp;
      return 0;
    }
  } else if (! SvOK(sv)) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return 0;
  } else if (SvTYPE(sv) == SVt_RV) {  /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return 0;
    else
      return -1;
  } else {                            /* Don't know what it is */
      *(ptr) = (void *) 0;
      return -1;
  }
  if (_t) {
    /* Now see if the types match */      
    _c = HvNAME(SvSTASH(SvRV(sv)));
    tc = SWIG_TypeCheck(_c,_t);
    if (!tc) {
      *ptr = (void *) tmp;
      return -1;
    }
    *ptr = SWIG_TypeCast(tc,(void *)tmp);
    return 0;
  }
  *ptr = (void *) tmp;
  return 0;
}
#ifndef PERL_OBJECT
SWIGRUNTIME(void) 
SWIG_MakePtr(SV *sv, void *ptr, swig_type_info *t,int flags)
#else
#define SWIG_MakePtr(a,b,c,d) _SWIG_MakePtr(pPerl,a,b,c,d)
SWIGRUNTIME(void)
_SWIG_MakePtr(CPerlObj *pPerl, SV *sv, void *ptr, swig_type_info *t, int flags)
#endif
{
  sv_setref_pv(sv, (char *) t->name, ptr);
}

#endif

typedef XS(SwigPerlWrapper);
typedef SwigPerlWrapper *SwigPerlWrapperPtr;

/* Structure for command table */
typedef struct {
  const char         *name;
  SwigPerlWrapperPtr  wrapper;
} swig_command_info;

/* Information for constant table */

#define SWIG_INT     1
#define SWIG_FLOAT   2
#define SWIG_STRING  3
#define SWIG_POINTER 4
#define SWIG_BINARY  5

/* Constant information structure */
typedef struct swig_constant_info {
    int              type;
    const char      *name;
    long             lvalue;
    double           dvalue;
    void            *pvalue;
    swig_type_info **ptype;
} swig_constant_info;

#ifdef __cplusplus
}
#endif

/* Structure for variable table */
typedef struct {
  const char   *name;
  SwigMagicFunc   set;
  SwigMagicFunc   get;
  swig_type_info  **type;
} swig_variable_info;

/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
  #ifndef MULTIPLICITY 
       static void _swig_create_magic(SV *sv, char *name, int (*set)(SV *, MAGIC *), int \
(*get)(SV *,MAGIC *)) { 
  #else 
       static void _swig_create_magic(SV *sv, char *name, int (*set)(struct interpreter*,\
 SV *, MAGIC *), int (*get)(struct interpreter*, SV *,MAGIC *)) { 
  #endif 
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerlObj *pPerl, SV *sv, const char *name, int (CPerlObj::*set)(SV *, MAGIC *), int (CPerlObj::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',(char *) name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = (SwigMagicFuncHack) get;
  mg->mg_virtual->svt_set = (SwigMagicFuncHack) set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}






#ifdef do_open
  #undef do_open
#endif
#ifdef do_close
  #undef do_close
#endif
#ifdef scalar
  #undef scalar
#endif
#ifdef list
  #undef list
#endif
#ifdef apply
  #undef apply
#endif
#ifdef convert
  #undef convert
#endif
#ifdef Error
  #undef Error
#endif
#ifdef form
  #undef form
#endif
#ifdef vform
  #undef vform
#endif
#ifdef LABEL
  #undef LABEL
#endif
#ifdef METHOD
  #undef METHOD
#endif
#ifdef Move
  #undef Move
#endif
#ifdef yylex
  #undef yylex
#endif
#ifdef yyparse
  #undef yyparse
#endif
#ifdef yyerror
  #undef yyerror
#endif
#ifdef invert
  #undef invert
#endif
#ifdef ref
  #undef ref
#endif


/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_prelude_db_interface_t swig_types[0] 
#define  SWIGTYPE_p_idmef_criterion_t swig_types[1] 
#define  SWIGTYPE_p_idmef_message_t swig_types[2] 
#define  SWIGTYPE_p_prelude_sql_table_t swig_types[3] 
#define  SWIGTYPE_p_uint64_t swig_types[4] 
#define  SWIGTYPE_p_prelude_sql_row_t swig_types[5] 
#define  SWIGTYPE_p_prelude_db_connection_t swig_types[6] 
#define  SWIGTYPE_p_prelude_db_ident_list_t swig_types[7] 
#define  SWIGTYPE_p_idmef_selection_t swig_types[8] 
#define  SWIGTYPE_p_prelude_sql_connection_t swig_types[9] 
static swig_type_info *swig_types[11];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    boot_PreludeDB

#define SWIG_name   "PreludeDB::boot_PreludeDB"
#define SWIG_prefix "PreludeDB::"

#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
#ifndef MULTIPLICITY
SWIGEXPORT(void) SWIG_init (CV* cv);
#else
SWIGEXPORT(void) SWIG_init (pTHXo_ CV* cv);
#endif
#else
SWIGEXPORT(void) SWIG_init (CV *cv, CPerlObj *);
#endif


#include <libprelude/list.h>
#include <libprelude/idmef.h>
#include "db-type.h"
#include "sql-connection-data.h"
#include "sql.h"
#include "db-connection.h"
#include "db-connection-data.h"
#include "db-interface.h"
#include "db-interface-string.h"

#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_PreludeDB_var::
class _wrap_PreludeDB_var : public CPerlObj {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(pTHX_ SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

#ifdef __cplusplus
extern "C" {
#endif
XS(_wrap_prelude_db_init) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 0) || (items > 0)) {
            SWIG_croak("Usage: prelude_db_init();");
        }
        result = (int)prelude_db_init();
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_shutdown) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 0) || (items > 0)) {
            SWIG_croak("Usage: prelude_db_shutdown();");
        }
        result = (int)prelude_db_shutdown();
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_new_string) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        char *arg1 ;
        prelude_db_interface_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_new_string(conn_string);");
        }
        if (!SvOK((SV*) ST(0))) arg1 = 0;
        else arg1 = (char *) SvPV(ST(0), PL_na);
        result = (prelude_db_interface_t *)prelude_db_interface_new_string((char const *)arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_prelude_db_interface_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_connect) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_connect(interface);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_connect. Expected _p_prelude_db_interface_t");
            }
        }
        result = (int)prelude_db_interface_connect(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_disconnect) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_disconnect(interface);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_disconnect. Expected _p_prelude_db_interface_t");
            }
        }
        result = (int)prelude_db_interface_disconnect(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_get_connection) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        prelude_db_connection_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_get_connection(interface);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_get_connection. Expected _p_prelude_db_interface_t");
            }
        }
        result = (prelude_db_connection_t *)prelude_db_interface_get_connection(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_prelude_db_connection_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_destroy) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_destroy(iface);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_destroy. Expected _p_prelude_db_interface_t");
            }
        }
        prelude_db_interface_destroy(arg1);
        
        
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_get_ident_list) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        idmef_criterion_t *arg2 = (idmef_criterion_t *) 0 ;
        prelude_db_ident_list_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_db_interface_get_ident_list(interface,criterion);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_get_ident_list. Expected _p_prelude_db_interface_t");
            }
        }
        {
            if (SWIG_ConvertPtr(ST(1), (void **) &arg2, SWIGTYPE_p_idmef_criterion_t,0) < 0) {
                SWIG_croak("Type error in argument 2 of prelude_db_interface_get_ident_list. Expected _p_idmef_criterion_t");
            }
        }
        result = (prelude_db_ident_list_t *)prelude_db_interface_get_ident_list(arg1,arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_prelude_db_ident_list_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_free_ident_list) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_ident_list_t *arg1 = (prelude_db_ident_list_t *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_free_ident_list(message_list);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_ident_list_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_free_ident_list. Expected _p_prelude_db_ident_list_t");
            }
        }
        prelude_db_interface_free_ident_list(arg1);
        
        
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_get_next_ident) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_ident_list_t *arg1 = (prelude_db_ident_list_t *) 0 ;
        uint64_t result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_interface_get_next_ident(ident_list);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_ident_list_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_get_next_ident. Expected _p_prelude_db_ident_list_t");
            }
        }
        result = prelude_db_interface_get_next_ident(arg1);
        
        {
            /* 	ST(argvi) = newSViv(result); */
            char tmp[32];
            int len;
            
            len = sprintf(tmp, "%llu", result);
            ST(argvi) = sv_2mortal(newSVpv(tmp, len));
            argvi++;
        }
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_get_alert) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        uint64_t arg2 ;
        idmef_selection_t *arg3 = (idmef_selection_t *) 0 ;
        idmef_message_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 3) || (items > 3)) {
            SWIG_croak("Usage: prelude_db_interface_get_alert(interface,ident,selection);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_get_alert. Expected _p_prelude_db_interface_t");
            }
        }
        {
            /* 	arg2 = (uint64_t) SvUV(ST(1)); */
            /* 	if ( SvIOK(ST(1)) ) { */
            /* 		printf("debug1.1: %u\n", SvUV(ST(1))); */
            /* 		arg2 = (uint64_t) SvUV(ST(1)); */
            
            /* 	} else { */
            /* 		printf("debug1.2: %s\n", SvPV_nolen(ST(1))); */
            sscanf(SvPV_nolen(ST(1)), "%llu", &(arg2));
            /* 	} */
        }
        {
            if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_idmef_selection_t,0) < 0) {
                SWIG_croak("Type error in argument 3 of prelude_db_interface_get_alert. Expected _p_idmef_selection_t");
            }
        }
        result = (idmef_message_t *)prelude_db_interface_get_alert(arg1,arg2,arg3);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_idmef_message_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_get_heartbeat) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        uint64_t arg2 ;
        idmef_selection_t *arg3 = (idmef_selection_t *) 0 ;
        idmef_message_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 3) || (items > 3)) {
            SWIG_croak("Usage: prelude_db_interface_get_heartbeat(interface,ident,selection);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_get_heartbeat. Expected _p_prelude_db_interface_t");
            }
        }
        {
            /* 	arg2 = (uint64_t) SvUV(ST(1)); */
            /* 	if ( SvIOK(ST(1)) ) { */
            /* 		printf("debug1.1: %u\n", SvUV(ST(1))); */
            /* 		arg2 = (uint64_t) SvUV(ST(1)); */
            
            /* 	} else { */
            /* 		printf("debug1.2: %s\n", SvPV_nolen(ST(1))); */
            sscanf(SvPV_nolen(ST(1)), "%llu", &(arg2));
            /* 	} */
        }
        {
            if (SWIG_ConvertPtr(ST(2), (void **) &arg3, SWIGTYPE_p_idmef_selection_t,0) < 0) {
                SWIG_croak("Type error in argument 3 of prelude_db_interface_get_heartbeat. Expected _p_idmef_selection_t");
            }
        }
        result = (idmef_message_t *)prelude_db_interface_get_heartbeat(arg1,arg2,arg3);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_idmef_message_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_delete_alert) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        int arg2 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_db_interface_delete_alert(interface,ident);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_delete_alert. Expected _p_prelude_db_interface_t");
            }
        }
        arg2 = (int) SvIV(ST(1));
        result = (int)prelude_db_interface_delete_alert(arg1,arg2);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_delete_heartbeat) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        int arg2 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_db_interface_delete_heartbeat(interface,ident);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_delete_heartbeat. Expected _p_prelude_db_interface_t");
            }
        }
        arg2 = (int) SvIV(ST(1));
        result = (int)prelude_db_interface_delete_heartbeat(arg1,arg2);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_interface_insert_idmef_message) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_interface_t *arg1 = (prelude_db_interface_t *) 0 ;
        idmef_message_t *arg2 = (idmef_message_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_db_interface_insert_idmef_message(interface,msg);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_interface_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_interface_insert_idmef_message. Expected _p_prelude_db_interface_t");
            }
        }
        {
            if (SWIG_ConvertPtr(ST(1), (void **) &arg2, SWIGTYPE_p_idmef_message_t,0) < 0) {
                SWIG_croak("Type error in argument 2 of prelude_db_interface_insert_idmef_message. Expected _p_idmef_message_t");
            }
        }
        result = (int)prelude_db_interface_insert_idmef_message(arg1,(idmef_message_t const *)arg2);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_connection_get_type) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_connection_t *arg1 = (prelude_db_connection_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_connection_get_type(dbconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_connection_get_type. Expected _p_prelude_db_connection_t");
            }
        }
        result = (int)prelude_db_connection_get_type(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_db_connection_get) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_db_connection_t *arg1 = (prelude_db_connection_t *) 0 ;
        prelude_sql_connection_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_db_connection_get(dbconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_db_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_db_connection_get. Expected _p_prelude_db_connection_t");
            }
        }
        result = (prelude_sql_connection_t *)prelude_db_connection_get(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_prelude_sql_connection_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_errno) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_errno(sqlconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_errno. Expected _p_prelude_sql_connection_t");
            }
        }
        result = (int)prelude_sql_errno(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_error) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        char *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_error(sqlconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_error. Expected _p_prelude_sql_connection_t");
            }
        }
        result = (char *)prelude_sql_error(arg1);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        }else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_query) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        char *arg2 ;
        prelude_sql_table_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_sql_query(sqlconn,query_string);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_query. Expected _p_prelude_sql_connection_t");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (prelude_sql_table_t *)prelude_sql_query(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_prelude_sql_table_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_begin) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_begin(sqlconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_begin. Expected _p_prelude_sql_connection_t");
            }
        }
        result = (int)prelude_sql_begin(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_commit) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_commit(sqlconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_commit. Expected _p_prelude_sql_connection_t");
            }
        }
        result = (int)prelude_sql_commit(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_rollback) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_rollback(sqlconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_rollback. Expected _p_prelude_sql_connection_t");
            }
        }
        result = (int)prelude_sql_rollback(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_escape) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        char *arg2 ;
        char *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_sql_escape(sqlconn,string);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_escape. Expected _p_prelude_sql_connection_t");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (char *)prelude_sql_escape(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        }else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_close) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_connection_t *arg1 = (prelude_sql_connection_t *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_close(sqlconn);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_connection_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_close. Expected _p_prelude_sql_connection_t");
            }
        }
        prelude_sql_close(arg1);
        
        
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_field_name) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
        int arg2 ;
        char *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_sql_field_name(table,i);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_field_name. Expected _p_prelude_sql_table_t");
            }
        }
        arg2 = (int) SvIV(ST(1));
        result = (char *)prelude_sql_field_name(arg1,arg2);
        
        ST(argvi) = sv_newmortal();
        if (result) {
            sv_setpv((SV*)ST(argvi++), (char *) result);
        }else {
            sv_setsv((SV*)ST(argvi++), &PL_sv_undef);
        }
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_field_num) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
        char *arg2 ;
        int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_sql_field_num(table,name);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_field_num. Expected _p_prelude_sql_table_t");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (int)prelude_sql_field_num(arg1,(char const *)arg2);
        
        ST(argvi) = sv_newmortal();
        sv_setiv(ST(argvi++), (IV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_fields_num) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
        unsigned int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_fields_num(table);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_fields_num. Expected _p_prelude_sql_table_t");
            }
        }
        result = (unsigned int)prelude_sql_fields_num(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setuv(ST(argvi++), (UV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_rows_num) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
        unsigned int result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_rows_num(table);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_rows_num. Expected _p_prelude_sql_table_t");
            }
        }
        result = (unsigned int)prelude_sql_rows_num(arg1);
        
        ST(argvi) = sv_newmortal();
        sv_setuv(ST(argvi++), (UV) result);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_row_fetch) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
        prelude_sql_row_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_row_fetch(table);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_row_fetch. Expected _p_prelude_sql_table_t");
            }
        }
        result = (prelude_sql_row_t *)prelude_sql_row_fetch(arg1);
        
        ST(argvi) = sv_newmortal();
        SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_prelude_sql_row_t,0);
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_table_free) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_table_t *arg1 = (prelude_sql_table_t *) 0 ;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 1) || (items > 1)) {
            SWIG_croak("Usage: prelude_sql_table_free(table);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_table_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_table_free. Expected _p_prelude_sql_table_t");
            }
        }
        prelude_sql_table_free(arg1);
        
        
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_field_fetch) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_row_t *arg1 = (prelude_sql_row_t *) 0 ;
        unsigned int arg2 ;
        prelude_sql_field_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_sql_field_fetch(row,i);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_row_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_field_fetch. Expected _p_prelude_sql_row_t");
            }
        }
        arg2 = (unsigned int) SvUV(ST(1));
        result = (prelude_sql_field_t *)prelude_sql_field_fetch(arg1,arg2);
        
        {
            switch ( prelude_sql_field_info_type(result) ) {
                case dbtype_int32:
                ST(argvi) = newSViv(prelude_sql_field_value_int32(result));
                argvi++;
                break;
                
                case dbtype_uint32:
                ST(argvi) = newSVuv(prelude_sql_field_value_uint32(result));
                argvi++;
                break;
                
                case dbtype_int64: case dbtype_uint64:
                ST(argvi) = newSVpv(prelude_sql_field_value(result), 0);
                argvi++;
                break;
                
                case dbtype_float:
                ST(argvi) = newSVnv((double) prelude_sql_field_value_float(result));
                argvi++;
                break;
                
                case dbtype_double:
                ST(argvi) = newSVnv(prelude_sql_field_value_double(result));
                argvi++;
                break;
                
                case dbtype_string:
                ST(argvi) = newSVpv(prelude_sql_field_value(result), 0);
                argvi++;
                break;
                
                default:
                /* nop */;
            }
        }
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}


XS(_wrap_prelude_sql_field_fetch_by_name) {
    char _swigmsg[SWIG_MAX_ERRMSG] = "";
    const char *_swigerr = _swigmsg;
    {
        prelude_sql_row_t *arg1 = (prelude_sql_row_t *) 0 ;
        char *arg2 ;
        prelude_sql_field_t *result;
        int argvi = 0;
        dXSARGS;
        
        if ((items < 2) || (items > 2)) {
            SWIG_croak("Usage: prelude_sql_field_fetch_by_name(row,name);");
        }
        {
            if (SWIG_ConvertPtr(ST(0), (void **) &arg1, SWIGTYPE_p_prelude_sql_row_t,0) < 0) {
                SWIG_croak("Type error in argument 1 of prelude_sql_field_fetch_by_name. Expected _p_prelude_sql_row_t");
            }
        }
        if (!SvOK((SV*) ST(1))) arg2 = 0;
        else arg2 = (char *) SvPV(ST(1), PL_na);
        result = (prelude_sql_field_t *)prelude_sql_field_fetch_by_name(arg1,(char const *)arg2);
        
        {
            switch ( prelude_sql_field_info_type(result) ) {
                case dbtype_int32:
                ST(argvi) = newSViv(prelude_sql_field_value_int32(result));
                argvi++;
                break;
                
                case dbtype_uint32:
                ST(argvi) = newSVuv(prelude_sql_field_value_uint32(result));
                argvi++;
                break;
                
                case dbtype_int64: case dbtype_uint64:
                ST(argvi) = newSVpv(prelude_sql_field_value(result), 0);
                argvi++;
                break;
                
                case dbtype_float:
                ST(argvi) = newSVnv((double) prelude_sql_field_value_float(result));
                argvi++;
                break;
                
                case dbtype_double:
                ST(argvi) = newSVnv(prelude_sql_field_value_double(result));
                argvi++;
                break;
                
                case dbtype_string:
                ST(argvi) = newSVpv(prelude_sql_field_value(result), 0);
                argvi++;
                break;
                
                default:
                /* nop */;
            }
        }
        XSRETURN(argvi);
        fail:
        (void) _swigerr;
    }
    croak(_swigerr);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_prelude_db_interface_t[] = {{"_p_prelude_db_interface_t", 0, "prelude_db_interface_t *", 0},{"_p_prelude_db_interface_t"},{0}};
static swig_type_info _swigt__p_idmef_criterion_t[] = {{"_p_idmef_criterion_t", 0, "idmef_criterion_t *", 0},{"_p_idmef_criterion_t"},{0}};
static swig_type_info _swigt__p_idmef_message_t[] = {{"_p_idmef_message_t", 0, "idmef_message_t *", 0},{"_p_idmef_message_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_table_t[] = {{"_p_prelude_sql_table_t", 0, "prelude_sql_table_t *", 0},{"_p_prelude_sql_table_t"},{0}};
static swig_type_info _swigt__p_uint64_t[] = {{"_p_uint64_t", 0, "uint64_t *", 0},{"_p_uint64_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_row_t[] = {{"_p_prelude_sql_row_t", 0, "prelude_sql_row_t *", 0},{"_p_prelude_sql_row_t"},{0}};
static swig_type_info _swigt__p_prelude_db_connection_t[] = {{"_p_prelude_db_connection_t", 0, "prelude_db_connection_t *", 0},{"_p_prelude_db_connection_t"},{0}};
static swig_type_info _swigt__p_prelude_db_ident_list_t[] = {{"_p_prelude_db_ident_list_t", 0, "prelude_db_ident_list_t *", 0},{"_p_prelude_db_ident_list_t"},{0}};
static swig_type_info _swigt__p_idmef_selection_t[] = {{"_p_idmef_selection_t", 0, "idmef_selection_t *", 0},{"_p_idmef_selection_t"},{0}};
static swig_type_info _swigt__p_prelude_sql_connection_t[] = {{"_p_prelude_sql_connection_t", 0, "prelude_sql_connection_t *", 0},{"_p_prelude_sql_connection_t"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_prelude_db_interface_t, 
_swigt__p_idmef_criterion_t, 
_swigt__p_idmef_message_t, 
_swigt__p_prelude_sql_table_t, 
_swigt__p_uint64_t, 
_swigt__p_prelude_sql_row_t, 
_swigt__p_prelude_db_connection_t, 
_swigt__p_prelude_db_ident_list_t, 
_swigt__p_idmef_selection_t, 
_swigt__p_prelude_sql_connection_t, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_constant_info swig_constants[] = {
{ SWIG_INT,     (char *) SWIG_prefix "prelude_db_type_invalid", (long) prelude_db_type_invalid, 0, 0, 0},
{ SWIG_INT,     (char *) SWIG_prefix "prelude_db_type_sql", (long) prelude_db_type_sql, 0, 0, 0},
{0}
};
#ifdef __cplusplus
}
#endif
static swig_variable_info swig_variables[] = {
{0}
};
static swig_command_info swig_commands[] = {
{"PreludeDB::prelude_db_init", _wrap_prelude_db_init},
{"PreludeDB::prelude_db_shutdown", _wrap_prelude_db_shutdown},
{"PreludeDB::prelude_db_interface_new_string", _wrap_prelude_db_interface_new_string},
{"PreludeDB::prelude_db_interface_connect", _wrap_prelude_db_interface_connect},
{"PreludeDB::prelude_db_interface_disconnect", _wrap_prelude_db_interface_disconnect},
{"PreludeDB::prelude_db_interface_get_connection", _wrap_prelude_db_interface_get_connection},
{"PreludeDB::prelude_db_interface_destroy", _wrap_prelude_db_interface_destroy},
{"PreludeDB::prelude_db_interface_get_ident_list", _wrap_prelude_db_interface_get_ident_list},
{"PreludeDB::prelude_db_interface_free_ident_list", _wrap_prelude_db_interface_free_ident_list},
{"PreludeDB::prelude_db_interface_get_next_ident", _wrap_prelude_db_interface_get_next_ident},
{"PreludeDB::prelude_db_interface_get_alert", _wrap_prelude_db_interface_get_alert},
{"PreludeDB::prelude_db_interface_get_heartbeat", _wrap_prelude_db_interface_get_heartbeat},
{"PreludeDB::prelude_db_interface_delete_alert", _wrap_prelude_db_interface_delete_alert},
{"PreludeDB::prelude_db_interface_delete_heartbeat", _wrap_prelude_db_interface_delete_heartbeat},
{"PreludeDB::prelude_db_interface_insert_idmef_message", _wrap_prelude_db_interface_insert_idmef_message},
{"PreludeDB::prelude_db_connection_get_type", _wrap_prelude_db_connection_get_type},
{"PreludeDB::prelude_db_connection_get", _wrap_prelude_db_connection_get},
{"PreludeDB::prelude_sql_errno", _wrap_prelude_sql_errno},
{"PreludeDB::prelude_sql_error", _wrap_prelude_sql_error},
{"PreludeDB::prelude_sql_query", _wrap_prelude_sql_query},
{"PreludeDB::prelude_sql_begin", _wrap_prelude_sql_begin},
{"PreludeDB::prelude_sql_commit", _wrap_prelude_sql_commit},
{"PreludeDB::prelude_sql_rollback", _wrap_prelude_sql_rollback},
{"PreludeDB::prelude_sql_escape", _wrap_prelude_sql_escape},
{"PreludeDB::prelude_sql_close", _wrap_prelude_sql_close},
{"PreludeDB::prelude_sql_field_name", _wrap_prelude_sql_field_name},
{"PreludeDB::prelude_sql_field_num", _wrap_prelude_sql_field_num},
{"PreludeDB::prelude_sql_fields_num", _wrap_prelude_sql_fields_num},
{"PreludeDB::prelude_sql_rows_num", _wrap_prelude_sql_rows_num},
{"PreludeDB::prelude_sql_row_fetch", _wrap_prelude_sql_row_fetch},
{"PreludeDB::prelude_sql_table_free", _wrap_prelude_sql_table_free},
{"PreludeDB::prelude_sql_field_fetch", _wrap_prelude_sql_field_fetch},
{"PreludeDB::prelude_sql_field_fetch_by_name", _wrap_prelude_sql_field_fetch_by_name},
{0,0}
};

#ifdef __cplusplus
extern "C"
#endif

XS(SWIG_init) {
    dXSARGS;
    int i;
    static int _init = 0;
    if (!_init) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        _init = 1;
    }
    
    /* Install commands */
    for (i = 0; swig_commands[i].name; i++) {
        newXS((char*) swig_commands[i].name,swig_commands[i].wrapper, (char*)__FILE__);
    }
    
    /* Install variables */
    for (i = 0; swig_variables[i].name; i++) {
        SV *sv;
        sv = perl_get_sv((char*) swig_variables[i].name, TRUE | 0x2);
        if (swig_variables[i].type) {
            SWIG_MakePtr(sv,(void *)1, *swig_variables[i].type,0);
        }else {
            sv_setiv(sv,(IV) 0);
        }
        swig_create_magic(sv, (char *) swig_variables[i].name, swig_variables[i].set, swig_variables[i].get); 
    }
    
    /* Install constant */
    for (i = 0; swig_constants[i].type; i++) {
        SV *sv;
        sv = perl_get_sv((char*)swig_constants[i].name, TRUE | 0x2);
        switch(swig_constants[i].type) {
            case SWIG_INT:
            sv_setiv(sv, (IV) swig_constants[i].lvalue);
            break;
            case SWIG_FLOAT:
            sv_setnv(sv, (double) swig_constants[i].dvalue);
            break;
            case SWIG_STRING:
            sv_setpv(sv, (char *) swig_constants[i].pvalue);
            break;
            case SWIG_POINTER:
            SWIG_MakePtr(sv, swig_constants[i].pvalue, *(swig_constants[i].ptype),0);
            break;
            case SWIG_BINARY:
            /*      obj = SWIG_NewPackedObj(swig_constants[i].pvalue, swig_constants[i].lvalue, *(swig_constants[i].ptype)); */
            break;
            default:
            break;
        }
        SvREADONLY_on(sv);
    }
    
    ST(0) = &PL_sv_yes;
    XSRETURN(1);
}

